InsightSoftwareConsortium/ITKPythonPackage

- .gitignore
- CMakeLists.txt
- README.md
- scripts/macpython-build-wheels.sh
- scripts/macpython-install-python.sh
> macOSX wheels scripts

- setup.py
This file name was changed from WrapITKBuildOptionsPython.py to
itkBuildOptions.py in ITK Change-Id:
I0137dda928e8d4090b3bb85ff04f09aea20a59ce
> setup.py: Update itkBuildOptions.py file name

- .gitignore
- CMakeLists.txt
- scripts/internal/manylinux-build-wheels.sh
This should be merged after:
http://review.source.kitware.com/#/c/22367
> ENH: Export ITK build trees on Linux

- scripts/dockcross-manylinux-build-module-wheels.sh
- scripts/dockcross-manylinux-build-wheels.sh
- scripts/macpython-build-common.sh
- scripts/macpython-build-module-wheels.sh
- scripts/macpython-build-wheels.sh
> macpython: add module wheels script

- scripts/dockcross-manylinux-download-cache-and-build-module-wheels.sh
Moving to the python packages used to build ITK wheels
> Moving to new python build packages

- scripts/internal/windows_build_common.py
- scripts/windows_build_module_wheels.py
The script now recreates and set up each virtual environment prior to the generation of the python wheels for windows
> ENH: Correction of the python wheel generator for windows

- docs/Quick_start_guide.rst
- docs/code/CastImageFilter.py
- docs/code/CompareITKTypes.py
- docs/code/CreateBaseline.py
- docs/code/ExplicitInstantiation.py
- docs/code/ImplicitInstantiation.py
- docs/code/InstantiateITKObjects.py
- docs/code/MixingITKAndNumPy.py
- docs/code/ReadMedianWrite.py
- docs/code/testDriver.py
- docs/index.rst
- requirements-dev.txt
- scripts/internal/manylinux-build-wheels.sh
- scripts/macpython-build-wheels.sh
- scripts/windows_build_wheels.py
The quick start guide illustrates how to do basic operations with ITK Python
such as reading and writing an image, and instantiating ITK objects.
A link to the ITK Sphinx example is also provided.
Suggested-by: Matt McCormick <matt.mccormick@kitware.com>
and Samuel Gerber <samuel.gerber@kitware.com>
> Addition of a Quick start quide

- docs/Build_ITK_Python_packages.rst
- docs/Quick_start_guide.rst
Addresses #67
Suggested-by: Addison Elliott <addison.elliott@gmail.com>
> docs: Add additional warning about Windows path length issue

- docs/index.rst
Also, remove the dollar sign from the commands to facilitate copy/paste.
> doc: Document how to install the nightly builds

- CMakeLists.txt
- scripts/dockcross-manylinux-build-module-wheels.sh
- scripts/dockcross-manylinux-download-cache-and-build-module-wheels.sh
- scripts/internal/manylinux-build-wheels.sh
- scripts/macpython-build-wheels.sh
- scripts/macpython-download-cache-and-build-module-wheels.sh
- scripts/windows-download-cache-and-build-module-wheels.ps1
- scripts/windows_build_wheels.py
Caveat: windows_build_wheels.py does not download and install doxygen,
> ENH: Generate Python docstrings from Doxygen documentation

- scripts/windows_build_wheels.py
Suggested-by: Jean-Christophe Fillion-Robin <jchris.fillionr@kitware.com>
> script: Style and readability improvementst to windows_build_wheels

- scripts/windows_build_module_wheels.py
> scripts: use check_call instead of check_output

- CMakeLists.txt
- scripts/internal/manylinux-build-module-wheels.sh
- scripts/internal/manylinux-build-wheels.sh
Depends on https://github.com/pypa/pypi-support/issues/341
> PERF: Build Linux with -O2 optimizations

- README.md
This is now most recently updated version.
> doc: README link point to Quick Start Guide master

- scripts/internal/manylinux-build-wheels.sh
- scripts/macpython-build-wheels.sh
- scripts/windows_build_wheels.py
See https://github.com/KitwareMedical/ITKUltrasound/issues/126.
> Enabling double without complex<double> leads to problems

- scripts/windows_build_module_wheels.py
Allow users to exclude libraries the module depends on, but which should
not be part of the wheel. e.g. The CUDA Driver library.
> ENH: Add option to exclude libs from repaired module wheel on Windows

- scripts/dockcross-manylinux-download-cache-and-build-module-wheels.sh
For building manylinux2014 wheels.
> ENH: Support custom dockcross remote module tarball name

- scripts/macpython-build-common.sh
- scripts/macpython-build-module-wheels.sh
- scripts/macpython-build-wheels.sh
In support of [https://github.com/InsightSoftwareConsortium/ITKElastix/pull/161](https://github.com/InsightSoftwareConsortium/ITKElastix/pull/161).
Tested and verified in [https://github.com/InsightSoftwareConsortium/ITKElastix/pull/161](https://github.com/InsightSoftwareConsortium/ITKElastix/pull/161): [https://github.com/InsightSoftwareConsortium/ITKElastix/runs/7886245285?check_suite_focus=true](https://github.com/InsightSoftwareConsortium/ITKElastix/runs/7886245285?check_suite_focus=true)
> ENH: Forward CMake arguments for MacOS builds

- scripts/macpython-build-module-wheels.sh
- scripts/macpython-build-wheels.sh
> Use MACOSX_DEPLOYMENT_TARGET if it is set

- scripts/macpython-build-common.sh
- scripts/macpython-build-wheels.sh
Fixes logic so that requesting a build for a certain version of Python can be correctly parsed.
> BUG: Fix macpython version request parsing

- scripts/dockcross-manylinux-build-module-wheels.sh
- scripts/dockcross-manylinux-build-wheels.sh
> COMP: Update dockcross for script versioning

- README.md
Adds table of contents and fixes a typo.
> DOC: Add table of contents to README

- scripts/internal/manylinux-build-module-wheels.sh
Following
https://github.com/InsightSoftwareConsortium/ITK/commit/bfc7f7b80051d05a32f18350cfadbbca36845e23 swig has an updated path and it is a pre-built binary.
Ideally we do not encode the version, but we should be moving beyond swig.
> COMP: Update Linux module build for binary swig

- CMakeLists.txt
References the same commit as the hash.
> ENH: Use 5.4rc03 for ITK_GIT_TAG

- requirements-dev.txt
- scripts/pyproject.toml.in
For remote module build usage.
Also bump scikit-build-core to latest.
> ENH: Install setuptools_scm

- scripts/internal/manylinux-build-module-wheels.sh
- BUG: Install both ITKPythonPackage and local module requirement-dev.txt
> linux pass config
