InsightSoftwareConsortium/ITKPythonPackage

- CMakeLists.txt
For faster builds and smaller packages.
> cmake: Use MinSizeRel CMAKE_BUILD_TYPE

- CMakeLists.txt
- scripts/internal/manylinux-build-wheels.sh
We should and have to do this in our scripts, so that a general build has
Release Build type and so skbuild does not clobber / specify the build type to
Release.
> Fix specification of CMAKE_BUILD_TYPE

- CMakeLists.txt
This is specified by scikit-build.
> Propagate CMAKE_BUILD_TYPE to ITK's configuration

- scripts/windows-build-wheels.ps1
Assumption is that Pythons are installed in folder like:
```
C:\PythonXY-x(64|86)
```
The script will build windows 64-bit wheels for Python 27
and Python 35.
> Add windows-build-wheels.ps1

- CMakeLists.txt
- scripts/windows-build-wheels.ps1
The full path is required to find ninja.exe when it is not in the path.
> Ensure CMAKE_MAKE_PROGRAM is passed into ExternalProjects

- README.md
This is the default from scikit-ci-addons and is more standard.
> Use 'latest' for GitHub releases instead of 'nightly'

- CMakeLists.txt
CMAKE_INSTALL_DO_STRIP is used in the cmake_install.cmake files to
determine whether to run the 'strip' executable on the C extension
binaries.
This reduces package size by about 15% on Unix-like systems.
> Strip libraries to decrease package size

- scripts/internal/manylinux-build-wheels.sh
- scripts/macpython-build-wheels.sh
The NumPy bridge is now enabled by default in the build, and loading all
the modules will result in an `import numpy` error otherwise.
> Install NumPy when testing virtualenv installs

- README.md
It was conveniently generated using https://github.com/ekalinin/github-markdown-toc
> README: Add table of content

- scripts/macpython-build-wheels.sh
This causes as duplicate build.
> macosx: skip the "Current" framework

- scripts/macpython-build-common.sh
- scripts/macpython-build-module-wheels.sh
- scripts/macpython-build-wheels.sh
In the itk wheels build, the venv's are not available until after they are
created in the itk build script. VENVS[0] are not necessarily the same between
runs -- ensure the tools are always present in the module wheel build script.
> macpython: improve tool install logic

- scripts/macpython-download-cache-and-build-module-wheels.sh
To prevent timeouts on TravisCI
CC: @jbvimort
> mac-module-wheels: use dot progress during download

- scripts/macpython-download-cache-and-build-module-wheels.sh
To prevent timeouts on TravisCI, aria2 with parallel downloads is
faster than wget.
> module-script: Improve binary download speed

- docs/Build_ITK_Module_Python_packages.rst
By default, gpg will only sign the first file given.
> Update gpg command for signing multiple wheels

- scripts/macpython-build-module-wheels.sh
Should not be necessarily unless there are third party library dependencies.
xref: #78
> macpython: Disable delocate for module wheel builds

- scripts/windows-download-cache-and-build-module-wheels.ps1
Adding of a new line in order to re-install the different version of python (with the good revision) on Appveyor
> ENH: Fixing the windows python wheels automatic generation scripts

- scripts/dockcross-manylinux-build-tarball.sh
- scripts/macpython-build-tarball.sh
- scripts/windows-build-tarball.ps1
These contain the ITK Python package build trees. ITK external module GitHub
CI builds download these tarballs and build against them.
> ENH: Add scripts to generate the ITKPythonBuilds-* tarballs

- scripts/dockcross-manylinux-build-module-wheels.sh
} -> )
Also fix up use of $script_dir
> BUG: Fix parenthesis type in linux module build wheels script

- scripts/internal/manylinux-build-module-wheels.sh
cp34 in no longer necessary for support because of low usage.
cpython-2.6.9-ucs2  cpython-2.6.9-ucs4 were recently added to the manylinux
image -- exclude them.
> manylinux: Update excluded Python versions

- scripts/macpython-build-module-wheels.sh
This reverts commit 3ba3aeb10e174ac630f28e9e172fa5dd4ce1183c.
Addresses #80
> Revert "macpython: Disable delocate for module wheel builds"

- docs/Build_ITK_Module_Python_packages.rst
- docs/Build_ITK_Python_packages.rst
- scripts/internal/windows_build_common.py
- scripts/windows-download-cache-and-build-module-wheels.ps1
- scripts/windows_build_wheels.py
ITKv5 will require C++11. On Windows, to compile ITK to work with Python2.7
from Python.org, one needs to use Visual Studio C++ 2008 which does not
support C++11. Therefore ITK will not be built on Windows for Python 2.7
anymore.
> WIP: Remove support for Python 2.7 on Windows

- scripts/macpython-build-module-wheels.sh
- scripts/macpython-build-wheels.sh
ITK 5 will require C++11. OSX_DEPLOYMENT_TARGET set to 10.9 uses libc++
instead of libstdc++ by default, which has sufficient C++11.
> macpython: Update CMAKE_OSX_DEPLOYMENT_TARGET to 10.9

- CMakeLists.txt
This fixes building the monolithic "itk" Python package because we
define the variable before the checks like:
if(NOT ITKPythonPackage_WHEEL_NAME STREQUAL "itk")
> CMakeLists.txt: set ITKPythonPackage_WHEEL_NAME earlier

- docs/Build_ITK_Module_Python_packages.rst
The signing was not verified, and signing is being removed from the
Python packaging tools.
> docs: Do not sign generated wheels

- scripts/windows_build_module_wheels.py
- scripts/windows_build_wheels.py
This should be in the primary ITK build script, not the module build script.
> windows: unsigned short pixel type specification in wrong build script

- CMakeLists.txt
This module has been migrated into the ITK repository and renamed from
BridgeNumPy to ITKBridgeNumPy.
> BUG: Include ITKBridgeNumPy into itk-core package

- docs/index.rst
Also, install numpy beforehand because it may not be reachable with
`--no-index`.
> doc: Upgrade when installing the nightly packages

- scripts/setup_py_configure.py
This is especially important for recent pip where it does not upgrade
dependencies by default.
> setup.py: Add version dependencies for split packages

- scripts/windows-download-cache-and-build-module-wheels.ps1
It is already installed. This now resulting in the AppVeyor build error:
47 Installing pip using C:\Python35-x86\python.exe
48C:\projects\itkmorphologicalcontourinterpolation\windows-download-cache-and-build-module-wheels.ps1 : This command cannot be run due to the error: The system cannot find the file specified.
49At line:1 char:1
50+ .\windows-download-cache-and-build-module-wheels.ps1
51+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
52    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
53    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,windows-download-cache-and-build-module-wheels.ps1
54
55
56
57Command executed with exception: This command cannot be run due to the error: The system cannot find the file specified.
> windows: Do not install Python on AppVeyor

- scripts/windows-download-cache-and-build-module-wheels.ps1
midas3.kitware.com is no longer available.
The SSL configuration required is explained here:
https://stackoverflow.com/questions/36265534/invoke-webrequest-ssl-fails
Closes #112
> windows-download-script: Download grep-win.zip from data.kitware.com

- scripts/windows-download-cache-and-build-module-wheels.ps1
Avoid errors related to unsupported protocol.
@jcfr FYI, we need this now for GitHub in addition to data.kitware.com.
> scripts: Enable TLS2 for GitHub downloads in PowerShell script

- scripts/internal/windows_build_common.py
- scripts/windows_build_wheels.py
> windows: Add basic argument parsing to driver script

- CMakeLists.txt
To address:
CMake Error at CMakeLists.txt:84 (message):
ITK source code directory path length is too long (54 > 50).Please move the
ITK source code directory to a directory with a shorter path.
-- Configuring incomplete, errors occurred!
See also "C:/P/IPP/_skbuild/win-amd64-3.5/cmake-build/ITK-build/CMakeFiles/CMakeOutput.log".
FAILED: ITK-prefix/src/ITK-stamp/ITK-configure
cmd.exe /C "cd /D C:\P\IPP\_skbuild\win-amd64-3.5\cmake-build\ITK-build && C:\P\IPP\venv-35-x64\Lib\site-packages\cmake\data\bin\cmake.exe -CC:/P/IPP/_skbuild/win-amd64-3.5/cmake-build/ITK-prefix/tmp/ITK-cache-Release.cmake -GNinja C:/P/IPP/_skbuild/win-amd64-3.5/cmake-build/ITK-source && C:\P\IPP\venv-35-x64\Lib\site-packages\cmake\data\bin\cmake.exe -E touch …
> COMP: Use a shorter ExternalProject prefix

- CMakeLists.txt
- scripts/windows_build_wheels.py
@fbudin69500 Could you please take this branch and run with it?
Todos:
<s> - [ ] Only enable `ITK_WRAP_DOC` if `DOXYGEN_EXECUTABLE` is available </s> pushed to Issue #116 
<s> - [ ] Do a better job at finding `DOXYGEN_EXECUTABLE` </s> pushed to Issue #116
> Superbuild: Pass additional ITK CMake configuration options

- CMakeLists.txt
When installing ITK from source (sdist), the CMakeLists.txt
file provided at the root of the project is used. This CMakeLists.txt file
uses the CMake variable `DOXYGEN_EXECUTABLE` assuming that it has been set
,which is the case when compiling ITKPythonPackage using the scripts available
in the `scripts` subdirectory. However, when building ITK from source, this
value was not set and compilation was failing with the following error message:
`Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)`
> cmake: Fix missing `find_package(Doxygen)`

- scripts/setup_py_configure.py
`>=` to `==` so versions are consistent.
> setup.py: Use strict version dependency for group wheels

- docs/Build_ITK_Module_Python_packages.rst
- docs/Build_ITK_Python_packages.rst
- scripts/windows-download-cache-and-build-module-wheels.ps1
This commit works around issue building ITKModuleTemplate wheels on
Azure Pipelines where 32-bit install of python is failing when using the
script provided by scikit-ci-addons.
See https://dev.azure.com/InsightSoftwareConsortium/ITKModules/_build/results?buildId=322
> Build only 64-bit wheels

- scripts/setup_py_configure.py
The Python file `itkHelpers.py` has been added recently to ITK but it
was not installed correctly with ITKPythonPackage. This commit
addresses this omission and should address ITKPythonPackage
issue #128 .
> scripts: install itkHelpers.py

- requirements-dev.txt
Required until https://github.com/scikit-build/scikit-build/issues/415
is addressed.
> requirements: Pin scikit-build version to 0.8.1

- docs/Build_ITK_Module_Python_packages.rst
Describes where to find wheels for initial upload.
Distinguishes short module name (e.g., itk-spcn) from long module name (e.g., ITKColorNormalization).
Gives URL for PyPI page to Add API Token.
Describes protocol for choosing an API token's name and scope.
Indicate that an unlimited scope can be used, if necessary, with caution.
Indicates that it is the upstream repository (github.com/InsightSoftwareConsortium/...) where the secret should be saved, rather than the user's fork of that repository.
Gives advice on appropriate version numbers for packages.
> DOC: Clarify Automate PyPI Package Uploads

- CMakeLists.txt
- itkVersion.py
- scripts/setup_py_configure.py
- setup.py
I think we need numpy 1.20 for typing, which in turn requires Python 3.7+. Should we also add a note to main ITK repo that Python 3.6 is no longer supported?
> ENH: We now always depend on numpy, so specify that in setup.py

- CMakeLists.txt
ITK v5.3rc02 tag: [https://github.com/InsightSoftwareConsortium/ITK//tree/4c25e667a5](https://github.com/InsightSoftwareConsortium/ITK//tree/4c25e667a5)
Failures from building against old (v5.3rc01) ITK source as a result of the old tag: [https://github.com/KitwareMedical/ITKUltrasound/pull/161](https://github.com/KitwareMedical/ITKUltrasound/pull/161)
> BUG: Fix hash for ITK v5.3rc02

- CMakeLists.txt
- itkVersion.py
Use the tag directly and bump the Python package version for a new release.
> BUG: Update tag for v5.3 RC 2

- scripts/windows_build_module_wheels.py
Fix issue seen in [ITKUltrasound PR 161](https://github.com/KitwareMedical/ITKUltrasound/pull/161) [Windows Python build](https://github.com/KitwareMedical/ITKUltrasound/runs/4159492171?check_suite_focus=true) where empty list of libraries for fixup argument produces error from leading semicolon.
> BUG: Fix path list for library fixup on Windows

- scripts/windows_build_module_wheels.py
When repairing wheels on windows, the delve_wheel patch loading dlls is appended to the module __init__ file. Upon installation, this module __init__ file overrides ITK's __init__ file. Rename the module file to prevent conflicts.
ITK's __init__ file takes care of executing the renamed module file.
> BUG: Rename module __init__ file after repairing windows module wheel

- CMakeLists.txt
In most cases where the `double` pixel type is required we also want to enable `complex<double>` wrappings for filters dealing with complex types, such as FFT filters.
Partially addresses issue discussed in InsightSoftwareConsortium/ITK#2884 where building with ITKPythonPackage failed because FFT class wrappings assumed `complex<double>` is enabled if `double` is enabled. Subsequent fix will follow in ITK wrappings.
> ENH: Enable wrapping for complex double type by default

- scripts/dockcross-manylinux-download-cache-and-build-module-wheels.sh
- scripts/internal/auditwheel_whitelist_monkeypatch.py
- scripts/internal/manylinux-build-module-wheels.sh
Add argument parsing allowing users to:
- Forward CMake options to the module
- Add option to exclude libs from repaired wheel on Linux:
Some shared libraries like the CUDA driver library must be provided at
runtime. Hence, it must be excluded from the repaired wheel (while it
must be provide in LD_LIBRARY_PATH for the project to compile).
The optional python version is still sent as positional argument for
backward compatibility.
> Add argument parsing for Linux module wheels scripts

- docs/code/ImplicitInstantiation.py
Undoing a change which was part of 523327e5010a5dd380bac50e428a2e37b7479b63.
> DOC: Restoring the example which demonstrated named parameters

- scripts/dockcross-manylinux-build-tarball.sh
- scripts/macpython-download-cache-and-build-module-wheels.sh
Comparing the `--help` output between zstd 1.2.0 and 1.5.2 shows that the `--long` option is not supported by the former. Without this option the Linux tarball compresses to 1.88 GiB which is less than the 2 GiB limit.
In the future we will need to upgrade the zstd version we are distributing to ITK external modules for building Python wheels so that they can take advantage of new, advanced compression flags. For now it seems we can stick with zstd 1.2.0.
> BUG: Remove zstd compression args incompatible with 1.2.0

- CMakeLists.txt
- itkVersion.py
- scripts/dockcross-manylinux-build-module-wheels.sh
- scripts/dockcross-manylinux-build-wheels.sh
- scripts/internal/manylinux-build-common.sh
- scripts/internal/manylinux-build-module-wheels.sh
- scripts/internal/manylinux-build-wheels.sh
Motivation for this change is to build wheels with C++ ABI compatible with Slicer built using newer g++ having `_GLIBCXX_USE_CXX11_ABI` defaulting to `1`.
See https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html
Note that the latest Slicer release (5.0) is built using centos7 based [^1] environment having `_GLIBCXX_USE_CXX11_ABI` set to `0`.
[^1]: https://github.com/Slicer/SlicerBuildEnvironment#supported-build-environments
We should likely build wheels using both `manylinux2014` and `manylinux_2_28`.
As of 2022.06.22, this pull-request uses `2_24`, as commented [^2] by @henryiii, I will instead update dockcross [^3] to add `2_28` based image (instead of `2_24)`.
[^2]: https://github.com/pypa/manylinux/issues/1332#issuecomment-1157666846
[^3]: …
> Add support for multiple manylinux versions

- scripts/internal/manylinux-build-module-wheels.sh
This is required when chaining module builds. The latest module to be built
must know about all the headers of former modules.
Our use case is that CudaCommon generates an export header that is then required when building RTK. I guess this does not happen for [ITKUltrasound](https://github.com/KitwareMedical/ITKUltrasound/blob/v0.5.0/.github/workflows/build-test-package.yml#L170-L206) because all the modules it depends on are not generating export headers.
@dzenanz @thewtex Can you review this please?
@SimonRit FYI
> Remove clean step when building module wheels on Linux

- scripts/internal/manylinux-build-module-wheels.sh
Commit #c953dc0 removed the clean step to allow accessing configured files when the script exists. However, when running two consecutive builds for different tarball specialization, the 1st build directory must be cleaned to make sure all libs are rebuilt for the right platform.
> manylinux: clean the build directory before building wheels

- scripts/macpython-build-module-wheels.sh
This was not defined on macos arm, causing packaging errors due to the wrong install path. Tested both on amd64 and arm.
> COMP: Define CMAKE_INSTALL_LIBDIR for mac arm remote module builds

- scripts/internal/manylinux-build-module-wheels.sh
- scripts/windows_build_module_wheels.py
Followup to 5b055e4c3fb3e23effd9fe213de3e7bf52fd4ec0 applying library install path fix on Windows and Linux platforms.
ITKSplitComponents external module Windows and Linux CI are passing with this patch applied at https://github.com/tbirdso/ITKSplitComponents/actions/runs/3175403084/jobs/5173400266.
Once this is merged I will amend module build scripts in existing `v5.3rc04.post3` archives and re-upload so that the patch can be applied in external module CI pipelines.
> BUG: Fix library install path on Windows and Linux

- scripts/windows_build_module_wheels.py
The dash in the module name is automatically replaced by an underscore in the corresponding wheel file name.
This commit fixes the problem seen in https://github.com/SimonRit/RTK/actions/runs/3314648884/jobs/5474209928#step:6:2771. It was used to produce Windows [itk-rtk-cuda116 wheels](https://pypi.org/project/itk-rtk-cuda116/#files).
> ENH: Allow for dash in Windows Python module

- CMakeLists.txt
- scripts/macpython-build-wheels.sh
This commit is a follow-up of these commits:
* a5f774ba5 (ENH: Add TBB support to Linux wheels)
* 374c744a1 (ENH: Add macOS wheel TBB support)
* 037a326c1 (ENH: Build macOS module wheels with TBB support)
It ensures that oneTBB is built specifying the non-default options expected by oneTBB [^1] and it should ensure the library can be loaded on macOS >= 10.9.
[^1]: https://github.com/oneapi-src/oneTBB/blob/v2021.3.0/CMakeLists.txt#L32-L39
See https://discourse.itk.org/t/itk-5-3rc4-post3-failure-to-load-libtbb-library-observed-on-macos-10-13/5405/1#suggested-path-forward-3
> COMP: Ensure tbb library is built with the expected deployment target

- scripts/dockcross-manylinux-build-tarball.sh
- scripts/dockcross-manylinux-download-cache-and-build-module-wheels.sh
Changes:
- Add `--long=31` option for improved Linux build archive compression
- Verify that zstd is at least v1.3.2 where `--long` is introduced
- Remove zstd v1.2.0 download option
Required for v5.3rc04.post4 builds which add Python 3.11 archives. Without the `--long=31` option these archives are over the 2GB limit imposed by Github. With the `--long=31` option build archives are right at the threshold at about 1.97GB. https://github.com/InsightSoftwareConsortium/ITKPythonBuilds/releases/tag/v5.3rc04.post4
I have updated zstd on `blaster` via `sudo apt install zstd` such that the installed zstd/unzstd version is now v1.4.4. This PR introduces the requirement that `unzstd>1.3.2` is used to decompress archives for building module wheels on Linux.
Echoes compression options introduced in …
> ENH: Use minimum system zstd in Linux scripts

- scripts/dockcross-manylinux-download-cache-and-build-module-wheels.sh
- scripts/internal/manylinux-aarch64-build-module-wheels.sh
- scripts/manylinux_2_28_aarch64-build-module-wheels.sh
Addresses #207 
The download cache and run script change needs to be tested. We will update the remote module scripts accordingly with the 5.3.0 release.
> ENH: Add support for building Linux ARM module wheels

- requirements-dev.txt
- scripts/windows_build_module_wheels.py
Addresses ITK module issue detailed in https://github.com/scikit-build/scikit-build/issues/805
Will validate with experimental ITKRemoteModuleBuildPackageAction/ITKSplitComponents CI prior to merge
> BUG: Bump skbuild to 0.16.2 to resolve Windows build failures

- scripts/dockcross-manylinux-build-module-wheels.sh
- scripts/dockcross-manylinux-build-wheels.sh
These updated images add Net-wide Assembler (NASM). This is needed for building zarr packages.
> ENH: Update manylinux images to latest tagged version

- scripts/dockcross-manylinux-build-module-wheels.sh
- scripts/dockcross-manylinux-build-wheels.sh
- scripts/dockcross-manylinux-download-cache-and-build-module-wheels.sh
- scripts/internal/manylinux-build-common.sh
- scripts/internal/manylinux-build-module-wheels.sh
- scripts/internal/manylinux-build-wheels.sh
- scripts/macpython-download-cache-and-build-module-wheels.sh
- scripts/manylinux_2_28_aarch64-build-module-wheels.sh
- scripts/windows-download-cache-and-build-module-wheels.ps1
Several related updates:
- Adds update step to apply build script patches to ITKPythonBuilds packages
- Exposes manylinux parameters and resolves issue where wrong image was used with specialized tarballs
- Reverts manylinux image tag while awaiting fix for `sudo` issue tracked in https://github.com/InsightSoftwareConsortium/ITKPythonPackage/issues/235 and https://github.com/dockcross/dockcross/issues/746
These changes are tested at https://github.com/InsightSoftwareConsortium/ITKSplitComponents/actions/runs/3586129456
> ENH: Add build script update step to download script

- scripts/dockcross-manylinux-build-module-wheels.sh
- scripts/dockcross-manylinux-build-wheels.sh
This fixes the sudo error, and has NASM inside. In [zarrIO](https://github.com/dzenanz/ITKIOOMEZarrNGFF/actions/runs/3596251270/jobs/6056706899) module, it goes over NASM error which was appearing around build step 500, just to run into another error around build step 800.
> ENH: Update manylinux images to latest tagged version 20221201-fd49c08

- scripts/dockcross-manylinux-build-module-wheels.sh
- scripts/dockcross-manylinux-build-wheels.sh
- scripts/dockcross-manylinux-download-cache-and-build-module-wheels.sh
- scripts/internal/manylinux-build-module-wheels.sh
Includes downgrade back from `gcc-toolset-12` to `gcc-toolset-11` tools for compatibility with ITK v5.3.0 tarballs.
See discussion in https://github.com/InsightSoftwareConsortium/ITK/issues/3785
> ENH: Bump manylinux image tag

- scripts/dockcross-manylinux-build-module-wheels.sh
- scripts/dockcross-manylinux-build-wheels.sh
While `manylinux_2_28` and `manylinux2014` images are typically tagged together, a recent `manylinux_2_28` release addressing a _2_28 toolset compatibility issue was not paired with a `manylinux2014` release. This commit updates Linux build scripts to decouple the tag used for each image.
See also: https://hub.docker.com/u/dockcross
> BUG: Revert to valid `manylinux2014-x64` image tag

- scripts/dockcross-manylinux-download-cache-and-build-module-wheels.sh
- scripts/dockcross-manylinux-download-cache.sh
Separates step for pulling build artifacts into a standalone script that is called by the central download-and-build script. The modular approach allows ITK modules with more complex build steps (OpenCL, etc) to use the download script directly instead of forking and altering the download script, thus reducing the maintenance burden for those ITK modules.
Local test has passed, will test on ITKSplitComponents before merge.
EDIT: Testing at https://github.com/InsightSoftwareConsortium/ITKSplitComponents/actions/runs/3676857336
> ENH: Modular archive download script on Linux

- scripts/macpython-download-cache-and-build-module-wheels.sh
- scripts/windows-download-cache-and-build-module-wheels.ps1
These 3 commits are used to allow (and improve) RTK compilation with CUDA following the latest developments of ITKRemoteModuleBuildTestPackageAction, see RTKConsortium/RTK#526. I haven't worked on specific options for each itk-module-deps (yet, I'm not sure it will be required for RTKConsortium/RTK#492)...
> Pass option to setup.py and cmake on Windows, clean-up and avoid unnecessary downloads

- scripts/windows-download-cache-and-build-module-wheels.ps1
This PR aims at improving the management of arguments in `windows-download-cache-and-build-module-wheels.ps1` following problems encountered in  RTKConsortium/RTK#535, namely passing multiple cmake options on the command line. The difference in the behaviors of PowerShell and Python args calls for another scripting language in my opinion (see #250 discussion) but this PR is an improvement over #248 in terms of clarity and consistency with other platforms. It is not backward compatible with it but that is probably ok since it is a recent change. See https://github.com/RTKConsortium/RTK/actions/runs/4243933294/jobs/7377339692 and https://github.com/RTKConsortium/RTK/actions/runs/4243933347 for successful use.
> ENH: Name and type command line options of Windows module PowerShell script

- scripts/dockcross-manylinux-build-module-deps.sh
First commit is required when there are spaces in some options of `dockcross-manylinux-download-cache-and-build-module-wheels.sh` (e.g. [here](https://github.com/RTKConsortium/RTK/blob/master/.github/workflows/build-test-package-python-cuda.yml#L6)).
Second  commit is required when the dependencies use generated include files (e.g. the `ModuleExport.h`).
These two changes where required to build RTK with external CudaCommon module. See first failure due to problem with options [here](https://github.com/RTKConsortium/RTK/actions/runs/4378694689/jobs/7663759417#step:4:31), second failure due to missing CudaCommonExport.h [here](https://github.com/RTKConsortium/RTK/actions/runs/4403309018/jobs/7711496893#step:4:1970) and [successful …
> Deps with args

- scripts/macpython-build-common.sh
- scripts/macpython-build-module-wheels.sh
- scripts/macpython-build-wheels.sh
This commit works around an issue with the "clean" command (see [1]) that was not properly considering the current MACOSX_DEPLOYMENT_TARGET env. variable.
It does by explicitly deleting the scikit-build directory without relying on the "setup.py clean" command not respecting the selected deployment target.
Considering that
1. the libraries installed while building the dependent itk-* wheels were accumulated in the install directory (e.g `_skbuild/macosx-X.Y-<arch>-3.9/setuptools/lib`)
2. the wheel is generated by systematically archiving the content of the install directory. The manifest files are used to select which file to "copy" into the install directory but these are not used by the function creating the wheel archive. See [2]
3. following …
> Fix macOS itk wheel size explicitly removing _skbuild directory

- scripts/windows-build-tarball.ps1
Crashing with the current version of 7zip:
```
$ powershell "IPP/scripts/windows-build-tarball.ps1"
7-Zip 23.01 (x64) : Copyright (c) 1999-2023 Igor Pavlov : 2023-06-20
Scanning the drive:
10059 folders, 152678 files, 9885141124 bytes (9428 MiB)
Creating archive: C:\P\ITKPythonBuilds-windows.zip
Add new data to archive: 10059 folders, 152678 files, 9885141124 bytes (9428 MiB)
System ERROR:
Internal Error: The failure in hardware (RAM or CPU), OS or program
```
The archive is small enough with recent improvements.
> BUG: Remove extra 7zip compression flags

- CMakeLists.txt
- scripts/internal/manylinux-aarch64-build-module-wheels.sh
- scripts/internal/manylinux-build-wheels.sh
We need to upgracde almalinux-release to get new GPG keys so we can install the sudo and ninja-build packages.
We need to update the cmake version for better Python Stable ABI support to build the 3.11 wheels.
We need to upgrade pip in the image so it knows how to install the Stable ABI wheels.
We no-longer remove the old wheels after running auditwheel because they start with the same name.
> COMP: Updates for linux aarch64 builds

- CMakeLists.txt
- itkVersion.py
- scripts/macpython-build-wheels.sh
ITK_GIT_TAG updated to tentative hash for v5.4rc04 tag.
> ENH: Bump version to 5.4rc4

- scripts/internal/manylinux-build-module-wheels.sh
- scripts/macpython-build-module-wheels.sh
- scripts/windows-download-cache-and-build-module-wheels.ps1
This is propagating to MacOS and Linux what's in Windows:
https://github.com/InsightSoftwareConsortium/ITKPythonPackage/blob/master/scripts/windows_build_module_wheels.py#L99
The Linux version has been tested in https://github.com/RTKConsortium/ITKCudaCommon/actions/runs/9275896116/job/25521657471. I haven't tested MacOS' version.
> BUG: Fix CMake options scikit-build-core on macOS and Linux

- scripts/dockcross-manylinux-build-module-deps.sh
- scripts/dockcross-manylinux-cleanup.sh
scikit-build compiles in the directory "_skbuild/cmake-build"
scikit-build-core compiles in an environment-dependent directory, e.g., in the directory "build/cp38-cp38-manylinux_2_28_x86_64"
> BUG: Fix compatibility with scikit-build(-core) build directory names

- scripts/macpython-download-cache-and-build-module-wheels.sh
Make `brew` work in quite mode to silence warnings.
Fixes:
```
Warning: Treating doxygen as a formula. For the cask, use homebrew/cask/doxygen or specify the `--cask` flag.
```
and
```
Warning: zstd 1.5.6 is already installed and up-to-date.
To reinstall 1.5.6, run:
brew reinstall zstd
```
and other similar warnings raised for example in:
https://github.com/InsightSoftwareConsortium/ITKAnalyzeObjectMap/actions/runs/10012233814
> ENH: Make `brew` work in quite mode to silence warnings

- scripts/macpython-download-cache-and-build-module-wheels.sh
The action started failing with the message:
```
tar: Option --checkpoint=10000 is not supported                                                                                             
```
See [here](https://github.com/RTKConsortium/RTK/actions/runs/10685686663/job/29619116447) for the result before the patch here [after](https://github.com/RTKConsortium/RTK/actions/runs/10689859485/job/29632952408) the patch.
> BUG: Use GNU tar instead of MacOS tar for checkpoint option

- scripts/macpython-download-cache-and-build-module-wheels.sh
The selection of directories is based on the compiled python versions.
This should fix disk usage issues in GH actions, see discussion [here](https://github.com/InsightSoftwareConsortium/ITKPythonPackage/pull/283#issuecomment-2329441023).
> ENH: Only extract required directories from the ITKPythonBuilds tar

- scripts/macpython-download-cache-and-build-module-wheels.sh
Fixes the following issue when building a module depending on another remote module:
mv: rename ITKPythonPackage to /Users/svc-dashboard/D/P/ITKPythonPackage: Directory not empty
> BUG: Remove existing IPP directory before moving

- scripts/macpython-download-cache-and-build-module-wheels.sh
Fixes the following issue when building a module depending on another remote module: mv: rename ITKPythonPackage to /Users/svc-dashboard/D/P/ITKPythonPackage: Directory not empty
> Backport: BUG: Do not move IPP if the directory already exists

- scripts/macpython-download-cache-and-build-module-wheels.sh
Reverts #287 and do not move IPP directory if it already exists as discussed in #288
> Fix macpython module deps

- scripts/macpython-download-cache-and-build-module-wheels.sh
Upgrade `rustup` in macOS Python module build script.
Fixes:
```
rustup is outdated!
To avoid broken installations, as soon as possible please run:
brew upgrade
Or, if you're OK with a less reliable fix: brew upgrade rustup
```
raised for example in:
https://github.com/InsightSoftwareConsortium/ITKAnalyzeObjectMap/actions/runs/10135042732
> ENH: Upgrade `rustup` in macOS Python module build script

- scripts/internal/manylinux-build-module-wheels.sh
mv is overwriting the manylinux wheel that auditwheel generated previously. This wheel contains the fixed up shared library that points to libtbb from the itk-core package. Otherwise, this will result in:
ImportError: libtbb.so.12: cannot open shared object file: No such file or directory
at runtime on systems without that library.
> BUG: Do not clobber auditwheel manylinux module wheel

- scripts/windows_build_module_wheels.py
The recent release of RTK v2.7.0 is not working properly on Windows because:
- without CUDA, the `__init_rtk__.py` file is overwritten
- with CUDA, the file is named `__init_rtk-cuda124__.py` because the wheel name is not the module name.
These two commits fix these issues.
> Fixups for `__init_module__.py` file

- scripts/macpython-build-module-wheels.sh
- scripts/macpython-build-tarball.sh
- scripts/macpython-download-cache-and-build-module-wheels.sh
ITK v5.4.3 has Intel MacOS wheels but the generation of module Intel MacOS wheels has been disabled per https://github.com/InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/commit/28c417088f004666921794227b08a75b0a8c19d4. This PR adresses the issue which was tracked down by
(1) adding the -v option to  `${Python3_EXECUTABLE} -m pip install --no-cache delocate` which indicated a problem in reading `ITKPythonPackage/venvs/3.11/lib/python3.11/site-packages/._distutils-precedence.pth`.
(2) calling `dot_clean` to remove all the MacOS specific `._*` files.
This has been tested in https://github.com/RTKConsortium/RTK/actions/runs/15493226615.
I know there won't be more Intel MacOS ITK wheels in the future but  in my opinion it's still worth building module wheels against ITK v5.4.3 …
> Module Intel MacOS wheels compilation

- scripts/dockcross-manylinux-build-module-deps.sh
- scripts/macpython-build-module-deps.sh
If a module has .in and .init wrapping files for generating code for a list of image types, they might be used in other modules. This happens in RTK using CudaCommon with CudaImage.i.in.
This patch has been tested in RTKConsortium/RTK#813 to test RTKConsortium/ITKCudaCommon#43.
cc @LucasGandel
> ENH: Copy .in and .init files of modules for use in other modules
